import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-col h-20 bg-gray-800">
          <h1 className="text-center pt-1 text-2xl">
            Planets App
          </h1>
          <nav className="flex items-center justify-around gap-5 mt-auto pb-1 ">
            <Link href={'/'} className="hover:text-blue-300">
              Home
            </Link>
            <Link href={'/planets'} className="hover:text-blue-300">
              Planetas
            </Link>
            <Link href={'/about'} className="hover:text-blue-300">
              Sobre
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
